#!/bin/bash

aur=yay
version="1.4-1"

while getopts "pydhvVzRPo:U" flag; do
	case $flag in
		p)
			aur=paru
			;;
		y)
			aur=yay
			;;
		o)
			aur=${OPTARG}
			;;
		R)
			$aur -Qq | awk '{print $1}' | sk --reverse --prompt "Remove Package: " --preview 'curl -s "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$(echo {} | tr -d "[:space:]")"' | $aur -R -
			exit 0
			;;
		P)
			$aur -Sl | awk '{print $2}' | sk --reverse --prompt "Get SRCINFO: " --preview 'curl -s "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$(echo {} | tr -d "[:space:]")"' | $aur -Si -
			exit 0
			;;

		d)
			$aur -Sl | awk '{print $2}' | sk --reverse --prompt "Get Package Description: " --preview 'curl -s "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$(echo {} | tr -d "[:space:]")"' | $aur -Si - | awk -F ": " 'FNR == 4 {print $2}'
			exit 0
			;;
		h)
			echo "
	zz: AUR Helper Helper

	Flags:
	-y                                            Uses yay as the AUR helper (default).
	-p                                                     Uses paru as the AUR helper.
	-o                                                           Use custom AUR helper.
	-R                                                        Removes selected package.
	-d                                                        Gets package description.
	-h                                                        Prints this help message.
	-v                                                                 Gets zz version.
	-V                                                   Gets selected package version.
	-z                                                   Shows only installed packages.
	-P                                                             Shows PKGBUILD info.
	-r                                                               Gets raw PKGBUILD.
			"
			exit 0
			;;
		v)
			echo "zz $version"
			exit 0
			;;
		V)
			$aur -Sl | awk '{print $2}' | sk --reverse --prompt "Get Package Version: " --preview 'curl -s "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$(echo {} | tr -d "[:space:]")"' | $aur -Si - | awk -F ": " 'FNR == 3 {print $2}'
			exit 0
			;;
		z)
			$aur -Qq | awk '{print $1}' | sk --reverse --prompt "Browse Installed Packages: " --preview 'curl -s "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$(echo {} | tr -d "[:space:]")"' | $aur -S -
			exit 0
			;;
		U)
			echo "-Sy (update sources)
-Syu (update sources & packages)
-Qn (shows all installed packages)
-Qm (lists every AUR package)
-Qdt (lists every orphaned package)
-Sc (clears package cache)" | sk --reverse --prompt "Choose Action: " | awk '{print $1}' |xargs $aur
			exit 0
			;;
		*)
			echo "Invalid flag."
			exit 1
			;;
	esac
done

if (( OPTIND == 1 )); then
	aur=$aur
fi

$aur -Sl | awk '{print $2}' | sk --reverse --prompt "zz: " --preview 'curl -s "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$(echo {} | tr -d "[:space:]")"' | $aur -S -
