#!/bin/bash

aur=yay
version=$($aur -Si zz | awk -F ": " 'FNR == 3 {print $2}')

while getopts "pydhvVzRPo:r" flag; do
	case $flag in
		p)
			aur=paru
			;;
		y)
			aur=yay
			;;
		o)
			aur=${OPTARG}
			;;
		R)
			$aur -Qn | awk '{print $1}' | fzf --layout reverse --border rounded | $aur -R -
			exit 0
			;;
		P)
			$aur -Sl | awk '{print $2}' | fzf --layout reverse --border rounded | $aur -Si -
			exit 0
			;;

		d)
			$aur -Sl | awk '{print $2}' | fzf --layout reverse --border rounded | $aur -Si - | awk -F ": " 'FNR == 4 {print $2}'
			exit 0
			;;
		r)
			pkg=$(yay -Sl | awk '{print $2}' | fzf --layout reverse --border rounded)
			curl https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$pkg
			exit 0
			;;
		h)
			echo "
	zz: AUR Helper Helper

	Flags:
	-y                                            Uses yay as the AUR helper (default).
	-p                                                     Uses paru as the AUR helper.
	-o                                                           Use custom AUR helper.
	-R                                                        Removes selected package.
	-d                                                        Gets package description.
	-h                                                        Prints this help message.
	-v                                                                 Gets zz version.
	-V                                                   Gets selected package version.
	-z                                                   Shows only installed packages.
	-P                                                             Shows PKGBUILD info.
	-r                                                               Gets raw PKGBUILD.
			"
			exit 0
			;;
		v)
			echo "zz $version"
			exit 0
			;;
		V)
			$aur -Sl | awk '{print $2}' | fzf --layout reverse --border rounded | $aur -Si - | awk -F ": " 'FNR == 3 {print $2}'
			exit 0
			;;
		z)
			$aur -Qn | awk '{print $1}' | fzf --layout reverse --border rounded | $aur -S -
			exit 0
			;;
		*)
			echo "Invalid flag."
			exit 1
			;;
	esac
done

if (( OPTIND == 1 )); then
	aur=yay
fi

$aur -Sl | awk '{print $2}' | fzf --layout reverse --border rounded | $aur -S -
